// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Newton.VideoGameCatalogue.Server;

#nullable disable

namespace Newton.VideoGameCatalogue.Server.Migrations
{
    [DbContext(typeof(GameContext))]
    partial class GameContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Newton.VideoGameCatalogue.Server.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Genre = "Strategy",
                            Rating = 8.8000000000000007,
                            ReleaseYear = 2006,
                            Title = "Total War: MEDIEVAL II"
                        },
                        new
                        {
                            Id = 2,
                            Genre = "Strategy",
                            Rating = 8.4000000000000004,
                            ReleaseYear = 2019,
                            Title = "Age of Empires II: Definitive Edition"
                        },
                        new
                        {
                            Id = 3,
                            Genre = "Survival",
                            Rating = 6.4000000000000004,
                            ReleaseYear = 2020,
                            Title = "Ancestors: The Humankind Odyssey"
                        },
                        new
                        {
                            Id = 4,
                            Genre = "RPG",
                            Rating = 8.0,
                            ReleaseYear = 2011,
                            Title = "Assassin's Creed Revelations"
                        },
                        new
                        {
                            Id = 5,
                            Genre = "RPG",
                            Rating = 7.2000000000000002,
                            ReleaseYear = 2019,
                            Title = "Assassin's Creed III Remastered"
                        },
                        new
                        {
                            Id = 6,
                            Genre = "RPG",
                            Rating = 8.3000000000000007,
                            ReleaseYear = 2018,
                            Title = "Assassin's Creed Odyssey"
                        },
                        new
                        {
                            Id = 7,
                            Genre = "RPG",
                            Rating = 8.3000000000000007,
                            ReleaseYear = 2017,
                            Title = "Assassin's Creed Origins"
                        },
                        new
                        {
                            Id = 8,
                            Genre = "FPS",
                            Rating = 9.8000000000000007,
                            ReleaseYear = 2003,
                            Title = "Call of Duty (2003)"
                        },
                        new
                        {
                            Id = 9,
                            Genre = "Board Game",
                            Rating = 6.0999999999999996,
                            ReleaseYear = 2017,
                            Title = "Catan Universe"
                        },
                        new
                        {
                            Id = 10,
                            Genre = "Strategy",
                            Rating = 8.5,
                            ReleaseYear = 2015,
                            Title = "Cities Skylines"
                        },
                        new
                        {
                            Id = 11,
                            Genre = "RPG",
                            Rating = 8.5999999999999996,
                            ReleaseYear = 2020,
                            Title = "Cyberpunk 2077"
                        },
                        new
                        {
                            Id = 12,
                            Genre = "Story",
                            Rating = 7.7999999999999998,
                            ReleaseYear = 2018,
                            Title = "Detroit: Become Human"
                        },
                        new
                        {
                            Id = 13,
                            Genre = "RPG",
                            Rating = 8.4000000000000004,
                            ReleaseYear = 2016,
                            Title = "The Elder Scrolls V: Skyrim Special Edition"
                        },
                        new
                        {
                            Id = 14,
                            Genre = "Strategy",
                            Rating = 8.6999999999999993,
                            ReleaseYear = 2013,
                            Title = "Europa Universalis IV"
                        },
                        new
                        {
                            Id = 15,
                            Genre = "Fighting",
                            Rating = 7.7999999999999998,
                            ReleaseYear = 2017,
                            Title = "FOR HONOR"
                        },
                        new
                        {
                            Id = 16,
                            Genre = "Open World",
                            Rating = 9.6999999999999993,
                            ReleaseYear = 2001,
                            Title = "Grand Theft Auto III"
                        },
                        new
                        {
                            Id = 17,
                            Genre = "Open World",
                            Rating = 9.5,
                            ReleaseYear = 2004,
                            Title = "Grand Theft Auto: San Andreas"
                        },
                        new
                        {
                            Id = 18,
                            Genre = "Open World",
                            Rating = 9.5,
                            ReleaseYear = 2002,
                            Title = "Grand Theft Auto: Vice City"
                        },
                        new
                        {
                            Id = 19,
                            Genre = "Strategy",
                            Rating = 8.3000000000000007,
                            ReleaseYear = 2015,
                            Title = "Kingdom: Classic"
                        },
                        new
                        {
                            Id = 20,
                            Genre = "RPG",
                            Rating = 8.8000000000000007,
                            ReleaseYear = 2025,
                            Title = "Kingdom Come: Deliverance II"
                        },
                        new
                        {
                            Id = 21,
                            Genre = "Puzzle",
                            Rating = 8.5999999999999996,
                            ReleaseYear = 2015,
                            Title = "Mini Metro"
                        },
                        new
                        {
                            Id = 22,
                            Genre = "Puzzle",
                            Rating = 8.6999999999999993,
                            ReleaseYear = 2021,
                            Title = "Mini Motorways"
                        },
                        new
                        {
                            Id = 23,
                            Genre = "Strategy",
                            Rating = 7.7000000000000002,
                            ReleaseYear = 2022,
                            Title = "Mount & Blade II: Bannerlord"
                        },
                        new
                        {
                            Id = 24,
                            Genre = "Strategy",
                            Rating = 8.5,
                            ReleaseYear = 2019,
                            Title = "Oxygen Not Included"
                        },
                        new
                        {
                            Id = 25,
                            Genre = "Puzzle",
                            Rating = 9.0,
                            ReleaseYear = 2007,
                            Title = "Portal"
                        },
                        new
                        {
                            Id = 26,
                            Genre = "Puzzle",
                            Rating = 9.5,
                            ReleaseYear = 2011,
                            Title = "Portal 2"
                        },
                        new
                        {
                            Id = 27,
                            Genre = "Action",
                            Rating = 6.9000000000000004,
                            ReleaseYear = 2020,
                            Title = "Raji: An Ancient Epic"
                        },
                        new
                        {
                            Id = 28,
                            Genre = "Souls-like",
                            Rating = 9.0,
                            ReleaseYear = 2019,
                            Title = "Sekiro: Shadows Die Twice"
                        },
                        new
                        {
                            Id = 29,
                            Genre = "Strategy",
                            Rating = 8.8000000000000007,
                            ReleaseYear = 2016,
                            Title = "Sid Meier's Civilization VI"
                        },
                        new
                        {
                            Id = 30,
                            Genre = "Puzzle",
                            Rating = 8.3000000000000007,
                            ReleaseYear = 2022,
                            Title = "Stray"
                        },
                        new
                        {
                            Id = 31,
                            Genre = "FPS",
                            Rating = 9.1999999999999993,
                            ReleaseYear = 2018,
                            Title = "Totally Accurate Battlegrounds"
                        },
                        new
                        {
                            Id = 32,
                            Genre = "RPG",
                            Rating = 9.1999999999999993,
                            ReleaseYear = 2015,
                            Title = "The Witcher 3: Wild Hunt"
                        },
                        new
                        {
                            Id = 33,
                            Genre = "Strategy",
                            Rating = 8.6999999999999993,
                            ReleaseYear = 2000,
                            Title = "Zeus: Master of Olympus"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
